apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: axanth-website
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/axanth1/workflow-k8s-configs.git
    targetRevision: HEAD
    path: 2-apps/axanth_website
  destination:
    server: https://kubernetes.default.svc
    namespace: axanth-website-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true