apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/axanth1/workflow-k8s-configs.git
    path: 1-cluster-setup/sealed-secrets
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    # The controller.yaml installs into the kube-system namespace by default
    namespace: kube-system 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true