---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gtm-server-config
  namespace: axanth-website-ns
spec:
  encryptedData:
    CONTAINER_CONFIG: AgA3ldRW7bK8QLEGhtlMPmYYp8r+Zk+madKMWZAiB1+tiu/NuPoON+ffSC9YXCa0InBIIs4aFWfne0SbK3jOl8g3pYkK0XGuNDwfhEe2L2vwZIRMRymaCex99WdUPp7C6jY1RpSRh52asz6P7uw1qGDjoQK/ZqrNhFD8JUIOhZL95td7+vt+DYS+RVorLWN70ImHjuOspaznYHVQTJNTz170a7U1xntCJ7jMb2szAfH4CKVV15S4h9A81cCtRXgisFurDfS92cgFOXqQCDOgfu8CsQqBQM18UCZinIRIfrYQxaKse0mdw+hfEkqGdUd3n7ZLCjsFRmIFJphwGAY4+2A2mz+VlvKK8bBTlsWKXAkh4PUfYYVYxbRSra1JjIj39hB+zSoNT4SIXWsZbi7wtPZsl5HsJwyydmKwsiBiCPvyxVA0pSoDvtz+zyGvPYcfMJODsG2ih61r8rEwTARSx/SEkXhESFMu1gW9Cx9ZtzsOHfdRGygJupaDsbTn+0ofOuZOCbFxP4p8zajruddaTeBdLjoKoAHpk6A/nLAoigINq34LszDKRM/7wKobYk1Wgp6FkcOkmhJKTsuW7cDPfOJnmIXjvmnXfGnrgvBdJ1s+mMY0DpPANhx11Maq+JXapiNx3uVLPQ9OvuiFTJCWyF5QpknsmkO/jjcKl5KPcwoWjDVc08skHwZP81XwdszEqptnWnTjkJNJZeYUfI8t2NvO8AC9WTs8xjkNG8W7rv2TygsLV2OB/M1IQ9RQ782vgOONiKX5v07rK4DNEKrLVmfiEr2Omw==
  template:
    metadata:
      creationTimestamp: null
      name: gtm-server-config
      namespace: axanth-website-ns
