apiVersion: apps/v1
kind: Deployment
metadata:
  name: axanth-website-deployment
  namespace: axanth-website-ns
spec:
  replicas: 3
  selector:
    matchLabels:
      app: axanth-website
  template:
    metadata:
      labels:
        app: axanth-website
    spec:
      containers:
        - name: axanth-website-container
          image: docker.io/axanth/axanth-website:e7411b54a21252407efae732fb5fd506503749bc
          ports:
            - containerPort: 3000
          # --- ADD THIS SECTION ---
          env:
            - name: RESEND_API_KEY
              valueFrom:
                secretKeyRef:
                  name: resend-secret
                  key: RESEND_API_KEY
          # ------------------------

          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
